SHELL=/bin/bash

#export EXTERNAL_VAR="server"

# ifdef EXTERNAL_VAR
# msg = Variable EXTERNAL_VAR is defined and set to $(EXTERNAL_VAR)
# else
# msg = Variable EXTERNAL_VAR is undefined
# endif

# all:
# 	@echo $(msg)

# CXX=c++
# START_OBJ = $(shell for o in crt{i,beginS}.o ; do $(CXX) -print-file-name=$$o ; done)

# all:
# 	@echo $(START_OBJ)

#MY_VAR=222

# var = `date '+%s'`

# define var
# `date '+%s'`
# endef

# l1 = a b c
# modules = `echo $(l1) | awk '{ gsub(/ /, ", "); printf "%s", $$0; }'`

make_var_value = 123456789

all:
	SHELL_VAR="shell_var-$(make_var_value)" ; echo $$SHELL_VAR


# @echo $(var)
# sleep 2s
# @echo $(var)
# sleep 2s
# @echo $(var)
# sleep 2s
# @echo $(var)
# sleep 2s
# @echo $(var)




